name: Yearly Experience Update
on:
  schedule:
    - cron: '0 0 1 9 *'  # Ejecutar el 1 de septiembre a las 00:00

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cloudflare Pages Deploy
        run: |
          curl -X POST "${{ secrets.CF_ANUAL_DEPLOY_HOOK }}" || exit 1